CREATE TABLE tDBGroups (id int,member varchar(50))
INSERT INTO tDBGroups (id,member) VALUES (1,'cn=Marc Boorshtein,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (1,'cn=Marc Johnson,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (1,'cn=Marc Jackson,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (1,'cn=Marc Allesy,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (2,'cn=Jack Boorshtein,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (2,'cn=Jack Johnson,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (2,'cn=Jack Jackson,ou=people,dc=domain,dc=com')
INSERT INTO tDBGroups (id,member) VALUES  (2,'cn=Jack Allesy,ou=people,dc=domain,dc=com')