CREATE TABLE GROUPS (id int,name varchar(255))
CREATE TABLE USERS (id int,login varchar(255),firstname varchar(255),lastname varchar(255),city varchar(255))
CREATE TABLE USERGROUPS (id int,userid int,groupid int)
INSERT INTO GROUPS VALUES (1,'users')
INSERT INTO GROUPS VALUES (2,'admins')
INSERT INTO USERGROUPS VALUES (1,3,1)
INSERT INTO USERGROUPS VALUES (2,3,2)
INSERT INTO USERGROUPS VALUES (3,4,1)
INSERT INTO USERS VALUES (1,'testuser0','Test','User','Arlington, VA')
INSERT INTO USERS VALUES (2,'testuser3','Test','User3','Arlington, VA')
INSERT INTO USERS VALUES (3,'testuser1','test','user1','Boston')
INSERT INTO USERS VALUES (4,'testuser2','test','user2','NY')